spring:
  application:
    name: flowforge-backend
  datasource:
    url: jdbc:mysql://localhost:3307/flowforge
    username: flowforge
    password: flowforge
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration